name: Publish Agora.Common.EFCore NuGet Package

on:
  push:
    paths:
      - 'Agora.Common.EFCore/**'
      - 'Agora.Common.EFCore.Tests/**'
      - '.github/workflows/publish-api.yml'
      - '.github/workflows/reusable-publish.yml'
  pull_request:
    paths:
      - 'Agora.Common.EFCore/**'
      - 'Agora.Common.EFCore.Tests/**'
      - '.github/workflows/publish-api.yml'
      - '.github/workflows/reusable-publish.yml'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/publish.yml
    with:
      project-path: Agora.Common.EFCore/Agora.Common.EFCore.csproj
      test-path: Agora.Common.EFCore.Tests/Agora.Common.EFCore.Tests.csproj
