name: Publish Agora.Common.Contracts NuGet Package

on:
  push:
    paths:
      - 'Agora.Common.Contracts/**'
      - 'Agora.Common.Contracts.Tests/**'
      - '.github/workflows/publish-api.yml'
      - '.github/workflows/publish.yml'
  pull_request:
    paths:
      - 'Agora.Common.Contracts/**'
      - 'Agora.Common.Contracts.Tests/**'
      - '.github/workflows/publish-api.yml'
      - '.github/workflows/publish.yml'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/publish.yml
    with:
      project-path: Agora.Common.Contracts/Agora.Common.Contracts.csproj
      test-path: Agora.Common.Contracts.Tests/Agora.Common.Contracts.Tests.csproj
