name: Publish Agora.Common.Api NuGet Package

on:
  push:
    paths:
      - 'Agora.Common.Api/**'
      - 'Agora.Common.Api.Tests/**'
      - '.github/workflows/publish-api.yml'
      - '.github/workflows/publish.yml'
  pull_request:
    paths:
      - 'Agora.Common.Api/**'
      - 'Agora.Common.Api.Tests/**'
      - '.github/workflows/publish-api.yml'
      - '.github/workflows/publish.yml'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/publish.yml
    with:
      project-path: Agora.Common.Api/Agora.Common.Api.csproj
      test-path: Agora.Common.Api.Tests/Agora.Common.Api.Tests.csproj
