name: Publish Agora.Common.Domain NuGet Package

on:
  push:
    paths:
      - 'Agora.Common.Domain/**'
      - 'Agora.Common.Domain.Tests/**'
      - '.github/workflows/publish-api.yml'
      - '.github/workflows/reusable-publish.yml'
  pull_request:
    paths:
      - 'Agora.Common.Domain/**'
      - 'Agora.Common.Domain.Tests/**'
      - '.github/workflows/publish-api.yml'
      - '.github/workflows/reusable-publish.yml'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/publish.yml
    with:
      project-path: Agora.Common.Domain/Agora.Common.Domain.csproj
      test-path: Agora.Common.Domain.Tests/Agora.Common.Domain.Tests.csproj
