name: Publish Agora.Common.Contracts NuGet Package

on:
  push:
    paths:
      - 'Agora.Common.Contracts/**'
  pull_request:
    paths:
      - 'Agora.Common.Contracts/**'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/publish.yml
    with:
      project-path: Agora.Common.Contracts/Agora.Common.Contracts.csproj
      test-path: Agora.Common.Contracts.Tests/Agora.Common.Contracts.Tests.csproj
