name: Reusable Publish Workflow

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string
      test-path:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Add GitHub Packages Source
        run: dotnet nuget add source \
          --username pmacn \
          --password ${{ secrets.NUGET_API_KEY }} \
          --store-password-in-clear-text \
          --name github \
          https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

      - name: Restore dependencies
        run: dotnet restore

      - name: Extract base version from .csproj
        id: extract-version
        run: |
          VERSION=$(xmllint --xpath "string(//Version)" ${{ inputs.project-path }})
          echo "VERSION=${VERSION}.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build project
        run: dotnet build ${{ inputs.project-path }} --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test ${{ inputs.test-path }} --configuration Release --no-build --verbosity normal

      - name: Pack project
        run: dotnet pack ${{ inputs.project-path }} --configuration Release --no-build --output ./nupkgs /p:Version=${{ env.VERSION }}

      - name: Publish package
        run: |
          for package in ./nupkgs/*.nupkg; do
            dotnet nuget push $package --api-key ${{ secrets.NUGET_API_KEY }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate
          done
