name: Publish NuGet Packages

on: 
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Pack projects
        run: |
          for proj in $(find . -name '*.csproj'); do
            dotnet pack $proj --configuration Release --no-build --output ./nupkgs
          done

      - name: Publish packages
        run: |
          for package in ./nupkgs/*.nupkg; do
            dotnet nuget push $package --api-key ${{ secrets.NUGET_API_KEY }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate
          done
